### ISSUE TITLE
Error load_mcmc_chains() - Object 'sampno' not found amongst V1, V2, V3, V4

### ISSUE THREAD

**Issue by kath-o-reilly** [seroanalytics/serosolver#52]
Hello, this error comes up when I've run my own analysis. It seems to come from the "..._chain_infection_histories.csv" file. There are no column names for the file generated. In the "example 2" the headers are "i,j,x,sampno". This is easy enough to copy and paste so I can kind-of fix it. But not sure why they weren't created in the first place...?

**Comment by jameshay218** [comment]
Hi Kath,

This sounds like a bug, as the correct column names should be getting created by default at L369 of R/mcmc.R when the infection history chain csv is created. Ultimately this line calls `data.table::fwrite`, and the first time its called it should be saving with `col.names=TRUE`.

Do you get the same issue with the README example?

Best,
James

**Comment by kath-o-reilly** [comment]
Hello - the colnames are generated fine in the README example...

For the inputs into run_MCMC would I add col.name=TRUE here somewhere maybe?

**Comment by jameshay218** [comment]
No, you shouldn't need to change the inputs to `run_MCMC`.

Are you running and saving multiple chains into the same directory simultaneously? Perhaps they are overwriting each other. If so you could try saving to a fresh directory and running one chain to see if the problem persists.

Does the `_chain_infection_histories.csv` file look OK otherwise? This sounds like it might also be an error where the MCMC proposals are not creating valid infection history matrices, and this is causing an issue. Another thought is that it could be an edge case that triggers a bug, for example causing an `fwrite` call with `col.names=TRUE` where it shouldn't. e.g. all proposed infection histories have 0 infections.

Two questions:
1. Can you share the `mcmc_pars` vector you are using? Or are you just using the default? There might be an odd interaction between some of the save settings.
2. If possible, do you have a minimal reproducible example? I know this might not be straightforward, but it would help.

Best,
James

**Comment by kath-o-reilly** [comment]
I don't think multiple re-write are the issue. `_chain_infection_histories.csv` looks ok but then I don't really know what it is meant to look like!

I'lll invite you to a private repo, if ok?

**Comment by jameshay218** [comment]
That'd be great! It should just have:

i: this gives the index of an individual, so you should see some rows for each `i` in your dataset
j: this is the time index of an infection time, so you should see rows for each time period in the model duration
x: this is somewhat redundant, as it should be a `1` for all entries. Downstream analyses assume that any missing i/j combination is a 0 (ie. it's a sparse matrix).
sampno: the MCMC iteration of the saved infection history matrix, should generally be of the same `min` and `max` as the `theta_chain` file.
